### ISSUE TITLE
tiptap-extesion is missing

### ISSUE THREAD

**Issue by alkeinaiduko** [scrumpy/tiptap#235]
i am trying to  install this plugin and then having a hard time to set it up to my project and then I found in the bottom of the docs that we need to import `tiptap-extensions` but I couldn't find it in `node_modules`. Please help!

**Comment by schnuet** [comment]
You can install the extensions using `npm install tiptap-extensions`. They are not automatically installed with tiptap itself.  
Stumbled other that one myself. But afterwards, everything worked as expected.

**Comment by erickwilder** [comment]
I'll add this to the docs so it is clear to everyone.

**Comment by alkeinaiduko** [comment]
@schnuet thank you for your reply, I just saw your reply today and I already fixed this the same as your solution. :+1:

**Comment by Ekkstein** [comment]
This still isn't clear from the documentation. Please consider the multiplied effort of all the users who have to find this and figure out, that the extensions need to be installed independently for this to work.

**Comment by Ekkstein** [comment]
This still isn't clear from the documentation. Please consider the multiplied effort of all the users who have to find this and figure out, that the extensions need to be installed independently for this to work.
