### ISSUE TITLE
Floating Menu does not always get updated on change

### ISSUE THREAD

**Issue by jackmcdade** [scrumpy/tiptap#260]
I've noticed that the `menu` data object in the `<editor-floating-menu>` component doesn't always get updated, especially if the updates are quick. If i wait about 300ms between events, it seems to always work, but anything less than that and i get mixed results (e.g. the `isActive` and `top` don't update).

Any ideas? Things to look into?

**Comment by philippkuehn** [comment]
Hey Jack. I tried typing as fast as possible but can't see any problems on the [example page](https://tiptap.scrumpy.io/floating-menu). Do you have these issue while typing? Or when using API methods? And which browser do you use?

**Comment by jackmcdade** [comment]
Ah, it's a mouse click thing. I'm on Chrome (73.0.3683.10). I can recreate it on the example page. Here's a video: <https://d.pr/v/heini9>

**Comment by philippkuehn** [comment]
Ah, see it. Looking into it!

**Comment by philippkuehn** [comment]
Okay this seems to be an issue with ProseMirror. [Created a thread in the discuss board](https://discuss.prosemirror.net/t/update-event-sometimes-not-fired/1881).

**Comment by jackmcdade** [comment]
Nice find. I'm watching that thread to see where it goes :)

**Comment by philippkuehn** [comment]
@jackmcdade this should be fixed in v1.15.0

**Comment by jackmcdade** [comment]
Awesome! We'll give it a test today.

**Comment by jackmcdade** [comment]
Updated to `1.15.0` but unfortunately still see the same exact behavior. Video in action:

<https://d.pr/v/QSryCR>

**Comment by jasonvarga** [comment]
Looks like [this is the same issue](https://github.com/ProseMirror/prosemirror/issues/909).

It was [fixed an hour ago](https://github.com/ProseMirror/prosemirror-view/commit/73e4eb9e9cdf5bb0c705953fed4eb683009bda2c) but a release hasn't been created yet.

We applied this patch locally and it seems to do the trick. (I'm working with @jackmcdade)

**Comment by philippkuehn** [comment]
Ah damn. Whatever I fixed then 😅
Let's wait for the ProseMirror release.

**Comment by philippkuehn** [comment]
With v1.16.1 this should be really fixed (with the newest version of prosemirror-view)
