### ISSUE TITLE
Bug after update to 1.19.0 : RangeError: Adding different instances of a keyed plugin (plugin$1)

### ISSUE THREAD

**Issue by ligne13** [scrumpy/tiptap#305]
I've updated tiptap from v1.8.0 to v1.19.0 and now I have this bug in the console :

> [Vue warn]: Error in data(): "RangeError: Adding different instances of a keyed plugin (plugin$1)"

The editor does not work anymore.

**Comment by philippkuehn** [comment]
try to make a clean install (remove node_modules).
if the issue still exists, please provide a codesandbox.

**Comment by ligne13** [comment]
Same bug after a clean install.
I do not have the bug in a basic sandbox... maybe a conflict with another dependency on code on my project. I will let you know if I find something.

**Comment by ligne13** [comment]
Hi @philippkuehn ,

the error is thrown by the prosemirror-state module, inside its EditorState.create method and the Configuration constructor, because 2 plugins have the same key (plugin$, whereas other plugins have an incremental key: plugin$1, plugin$2, etc.) : these plugins are handleTextInput and handleKeydown. 

See the screenshots below :
![image](https://user-images.githubusercontent.com/81624/57478258-c5c40a00-729a-11e9-96d8-8d4574fe4854.png)

![image](https://user-images.githubusercontent.com/81624/57478415-23f0ed00-729b-11e9-8645-ffedf7fce619.png)

Do you have an idea of what can cause this error ?

thanks

**Comment by philippkuehn** [comment]
do you add some custom extensions/plugins to your editor?

**Comment by ligne13** [comment]
Well, that is strange : now it's working. I have not changed anything. Just made a few more npm installs...

**Comment by xiongxiaocui** [comment]
> The

me too

**Comment by cbeninati** [comment]
Same for me.
I've cleared the yarn cache, removed `node_modules` and re-run `yarn install` multiple times.

**using:** yarn
**tiptap version:** 1.19.1

![Screen Shot 2019-05-10 at 8 11 39 PM](https://user-images.githubusercontent.com/1027918/57563820-da1e0a80-735f-11e9-81db-13c9baea926b.png)

**Comment by cbeninati** [comment]
I found out my problem. I had manually changed the versions for **tiptap** and **tiptap-extensions** to `^1/19.1`. After reverting to my latest commit and instead running `yarn upgrade`, it is working.

**Comment by bbbford** [comment]
Same issue for me. Unfortunately it hasn't resolved itself after a clean install..

**Comment by bbbford** [comment]
I am having this same problem. It is intermittent. Clean install did not solve the problem for me...

**Comment by Raerten** [comment]
Try to delete node_modules and yarn.lock, after run yarn install again

**Comment by bbbford** [comment]
Thanks @Raerten. I deleted node_modules folder and package-lock.json, then ran npm install. That seems to have done the trick. Thank you very much!

**Comment by julianfox** [comment]
I still get this error with a fresh install with:
"tiptap": "^1.26.6",
"tiptap-extensions": "^1.28.6"

Here my code:
`<template>
  <div class="tf-content-editor">
    <client-only placeholder="Loading...">
      <editor-floating-menu v-slot="{ commands, isActive, menu }" :editor="editor">
        <div
          class="editor__floating-menu"
          :class="{ 'is-active': menu.isActive }"
          :style="`top: ${menu.top}px`"
        >
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.heading({ level: 1 }) }"
            @click="commands.heading({ level: 1 })"
          >
            H1
          </button>
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.heading({ level: 2 }) }"
            @click="commands.heading({ level: 2 })"
          >
            H2
          </button>
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.heading({ level: 3 }) }"
            @click="commands.heading({ level: 3 })"
          >
            H3
          </button>
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.bullet_list() }"
            @click="commands.bullet_list"
          >
            <icon name="ul" />
          </button>
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.ordered_list() }"
            @click="commands.ordered_list"
          >
            <icon name="ol" />
          </button>
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.blockquote() }"
            @click="commands.blockquote"
          >
            <icon name="quote" />
          </button>
          <button
            class="menubar__button"
            :class="{ 'is-active': isActive.code_block() }"
            @click="commands.code_block"
          >
            <icon name="code" />
          </button>
        </div>
      </editor-floating-menu>
      <editor-content class="editor__content" :editor="editor" />
    </client-only>
  </div>
</template>

<script>
import { Editor, EditorContent, EditorFloatingMenu } from 'tiptap'
import {
  Blockquote,
  BulletList,
  CodeBlock,
  HardBreak,
  Heading,
  ListItem,
  OrderedList,
  TodoItem,
  TodoList,
  Bold,
  Code,
  Italic,
  Link,
  History
} from 'tiptap-extensions'

export default {
  components: {
    EditorContent,
    EditorFloatingMenu
  },
  data () {
    return {
      editor: null
    }
  },
  mounted () {
    this.editor = new Editor({
      extensions: [
        new Blockquote(),
        new BulletList(),
        new CodeBlock(),
        new HardBreak(),
        new Heading({ levels: [1, 2, 3] }),
        new ListItem(),
        new OrderedList(),
        new TodoItem(),
        new TodoList(),
        new Link(),
        new Bold(),
        new Code(),
        new Italic(),
        new History()
      ],
      content: `
        <h2>
          Floating Menu
        </h2>
        <p>
          This is an example of a medium-like editor. Enter a new line and some buttons will appear.
        </p>
      `
    })
  },
  beforeDestroy () {
    this.editor.destroy()
  }
}
</script>`

I've cleared the yarn cache, removed node_modules and re-run yarn install 1000 times and also run yarn upgrade without any success...

Is it can be related to the new version of Tiptap?

**Comment by latelt-j** [comment]
Same problem here

**Comment by homerager** [comment]
Have the same problem, removing node_modules did not help

**Comment by jakedolan** [comment]
Some further discussion on this here:
https://github.com/scrumpy/tiptap/issues/577#issuecomment-600851902

This appears related multiple versions of prosemirror-state being loaded. It can be worked around  by adding the following (yarn) resolutions in your package.json:

> "resolutions": {
>     "prosemirror-model": "1.8.2",
>     "prosemirror-state": "1.3.2",
>     "prosemirror-transform": "1.2.2",
>     "prosemirror-view": "1.13.4"
>   },
> To summarize, this is what I did:
> 
> Opened yarn.lock and found duplicates for every prosemirror package
> For every such package, pinpointed its version in resolutions to prevent multiple versions of the same package from installing (you can try my resolutions above)
> rm -rf node_modules
> yarn cache clean
> yarn install

**Comment by shadrachtuck** [comment]
@jakedolan thank you good sir!! worked like a charm

**Comment by doits** [comment]
@jakedolan thanks! Seems like js dependency management is a total mess if one needs to do stuff like this.

**Comment by lukkyjoe** [comment]
I do not understand the inner-workings deeply enough to be able to give an explanation. But I will say that removing `node_modules` was insufficient for me. But removing `node_modules` AND `package-lock.json` and re npm installing did the trick for me.

**Comment by BinaryBrain** [comment]
If you encounter this issue using `yarn workspace`, please note that the `resolution` code posted by @jakedolan must be placed in your project root `package.json` and **not** in a workspace `package.json`.

**Comment by mudin** [comment]
This is still happening

**Comment by jatarga** [comment]
Same problem. Doesnt work with following conditions:

```
"tiptap": "^1.26.6",
"tiptap-extensions": "^1.28.6",
vue": "^2.6.11"
```

**Comment by lehni** [comment]
See here for a work-around:
https://github.com/scrumpy/tiptap/issues/577#issuecomment-600865824

**Comment by mudin** [comment]
My problem is fixed. Actually I am using lerna and I removed tiptap from root package.json and keep only in single package where I use it. Maybe this will help someone who is also using lerna

**Comment by AdonisProios** [comment]
Still happens for me after:

`rm -rf node_modules yarn.lock && yarn cache clean && yarn install && yarn dev`

and the below in package.json:
```
"resolutions": {
    "prosemirror-model": "1.8.2",
    "prosemirror-state": "1.3.2",
    "prosemirror-transform": "1.2.2",
    "prosemirror-view": "1.13.4"
  },
```

```yarn list v1.22.4
├─ tiptap-commands@1.12.5
├─ tiptap-extensions@1.28.6
│  └─ tiptap@1.26.6
├─ tiptap-utils@1.8.3
└─ tiptap@1.26.4

├─ @vue/component-compiler-utils@3.1.1
├─ babel-helper-vue-jsx-merge-props@2.0.3
├─ vue-hot-reload-api@2.3.4
├─ vue-loader@15.9.1
├─ vue-router@3.1.6
├─ vue-style-loader@4.1.2
├─ vue-template-compiler@2.6.11
├─ vue-template-es2015-compiler@1.9.1
├─ vue@2.6.11
└─ vuex@3.1.3
```

The problem is intermittent. For example I can change some *text* string (say in `console.log()`) in my App.vue and it'll work (my page renders and no errors in the console), and sometimes it won't. As if there's some timing issue or somesuch..

**Comment by jatarga** [comment]
This comment on #577 fixed my issue: 

https://github.com/scrumpy/tiptap/issues/577#issuecomment-600865824

**Comment by A-d-o-n-i-s** [comment]
I tried it without any luck (it's all in my report above..), but thanks!

**Comment by jakedolan** [comment]
@A-d-o-n-i-s It appears that you are still loading multiple versions of prosemirror-state. 

├─ tiptap-commands@1.12.5
│  └─ **prosemirror-state@1.3.2**
├─ tiptap-extensions@1.28.6
│  ├─ prosemirror-gapcursor@1.1.2
│  │  ├─ **prosemirror-state@1.3.3**

For this workaround, you may need to investigate why your resolutions in the package.json is not enforcing the resolution to a single version of the prosemirror-state package.

**Comment by A-d-o-n-i-s** [comment]
Oh! I missed that. Thank you!

Any thoughts if this could be affecting things:

**Comment by prodigy7** [comment]
This bug is currently a absolut show stopper for me. Would be nice, see a fix!

**Comment by A-d-o-n-i-s** [comment]
Yes, totally agree! I'm being asked by my company to look at other editors now... This is a blow to Prosemirror and Tiptap and Vue.js...

**Comment by amraei** [comment]
For me, this occurred after running `npm audit fix --force`. I think there is a problem with `prosemirror` but I didn't investigated enough. Removing `node_modules` AND `package-lock.json` and then a fresh install solved it.

**Comment by panayotisk** [comment]
I has the same issue. I needed to import prosemirror-state and prosemirror-view because I had to modify some extensions. What finally worked for me was:
1. Remove everything tiptap and prosemirror related from package.json
2. Remove node_modules directory and package-lock.json
3. Run `npm install tiptap tiptap-extensions tiptap-commands prosemirror-state prosemirror-view`
4. Run `npm install`

Somehow the 1st step made a difference in my case.

**Comment by abusedmedia** [comment]
Same issue here and the @panayotisk advice worked for me as well.

**Comment by nicooprat** [comment]
Can confirm it too, without manually editing `package-lock.json` or installing ProseMirror related packages:

* `npm remove tiptap tiptap-commands tiptap-extensions`
* `rm -rf node_modules`
* `npm i -S tiptap tiptap-commands tiptap-extensions`

Finally fixed this months-long bug! 😌

**Comment by doits** [comment]
With latest `presemirror-model` `1.10.0` we are back at this again, at least with yarn. It installs version 1.9.1 and 1.10.0 and there it goes.

`tiptap-commands` explicitly requires version `1.9.1` (why that strict?), other dependents have it hard coded with a version range (e.g. `^1.1.0`).

I fixed it by forcing 1.10.0 for all packages in `package.json`, which seems to work out so far:

```json
{
  resolutions: {
    prosemirror-model: "~1.10.0"
  }
}
```

**Comment by maximecolin** [comment]
Got this error recently after updating dependencies. The error come from different installed versions of some prosemirror plugins.

Use `yarn list --pattern prosemirror` to see installed versions.

If you got something like this, several versions of the same plugin are installed:

```
yarn list v1.22.5
├─ prosemirror-collab@1.2.2
├─ prosemirror-commands@1.1.4
├─ prosemirror-dropcursor@1.3.2
├─ prosemirror-gapcursor@1.1.5
├─ prosemirror-history@1.1.3
├─ prosemirror-inputrules@1.1.3
├─ prosemirror-keymap@1.1.4
├─ prosemirror-model@1.13.1
├─ prosemirror-schema-list@1.1.4
├─ prosemirror-state@1.3.4
├─ prosemirror-tables@1.1.1
├─ prosemirror-transform@1.2.9
├─ prosemirror-utils@0.9.6
├─ prosemirror-view@1.17.2
├─ tiptap-commands@1.16.0
│  └─ prosemirror-commands@1.1.5
└─ tiptap@1.31.0
   ├─ prosemirror-state@1.3.3
   └─ prosemirror-view@1.16.5
      └─ prosemirror-state@1.3.4
```

Here `prosemirror-commands` 1.1.5 and 1.1.4, `prosemirror-state` 1.3.4 and 1.3.3 and `prosemirror-view` 1.17.2 and 1.16.5 are installed.

You can resolve this by using `resolutions` to force the versions of each plugin in order to install one unique version of each.

For exemple :

```
    "resolutions": {
        "prosemirror-commands": "1.1.5",
        "prosemirror-state": "1.3.4",
        "prosemirror-view": "1.17.2"
    }
```

Then `rm -Rf node_modules/` and `yarn install` / `npm install`.

Now, when running `yarn list --pattern prosemirror`, each plugin must appear once, like :

```
├─ prosemirror-collab@1.2.2
├─ prosemirror-commands@1.1.5
├─ prosemirror-dropcursor@1.3.2
├─ prosemirror-gapcursor@1.1.5
├─ prosemirror-history@1.1.3
├─ prosemirror-inputrules@1.1.3
├─ prosemirror-keymap@1.1.4
├─ prosemirror-model@1.13.1
├─ prosemirror-schema-list@1.1.4
├─ prosemirror-state@1.3.4
├─ prosemirror-tables@1.1.1
├─ prosemirror-transform@1.2.9
├─ prosemirror-utils@0.9.6
└─ prosemirror-view@1.17.2
```

**Comment by hanspagel** [comment]
Thanks! Seems to be the same as in #947. I’ll work on that one. ✌️

**Comment by gabrielstuff** [comment]
This appears to still be an issue with the demo page. Created a glitch sample there with code from documentation : 

```
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <div class="element"></div>
  <script type="module">
    import { Editor } from 'https://cdn.skypack.dev/@tiptap/core?min'
    import { defaultExtensions } from 'https://cdn.skypack.dev/@tiptap/starter-kit?min'
    const editor = new Editor({
      element: document.querySelector('.element'),
      extensions: defaultExtensions(),
      content: '<p>Hello World!</p>',
    })
  </script>
</body>
</html>
```

Error show : 

> prosemirror-state.js:1 Uncaught RangeError: Adding different instances of a keyed plugin (plugin$)
    at prosemirror-state.js:1
    at Array.forEach (<anonymous>)
    at new I (prosemirror-state.js:1)
    at p.reconfigure (prosemirror-state.js:1)
    at ur.createView (core.js:65)
    at new ur (core.js:65)
    at (index):11

See example here:
https://tiptap-starter-demo.glitch.me/

**Comment by gryzzly** [comment]
I just followed a "quick start" here – https://www.tiptap.dev/installation/cdn and copied the code from the example and the reported error is the first thing I saw:

Code:
```
    import { Editor } from 'https://cdn.skypack.dev/@tiptap/core?min'
    import StarterKit from 'https://cdn.skypack.dev/@tiptap/starter-kit?min'
    const editor = new Editor({
      element: document.querySelector('.element'),
      extensions: [
        StarterKit,
      ],
      content: '<p>Hello World!</p>',
    })
```
Error:
```
Uncaught RangeError: Adding different instances of a keyed plugin (plugin$)
```

**Comment by legendarylion** [comment]
Removing node_modules and package_lock.json, then completing a fresh install `npm install && npm run watch` resolved the issue for me.

**Comment by WeTurkstra** [comment]
I had the same problem. I found it related to using the editor.isActive() function. 
When i removed any of these statements in my template the error did not occure.

**Comment by accolver** [comment]
I got the error when I added an extension that was part of the `StarterKit` (e.g. the History extension). Simply removing the redundant package fixed it.

**Comment by Abdulrahmanelheyb** [comment]
RangeError: Adding different instances of a keyed plugin (history$)
this problem means is have two instances of the same extension in the editor, To solve the problem you need to remove the second instance of the extension 

My Example:
I added StarterKit firstly and I added the History plugin I get this error now when adding StarterKit and History together
I removed the History plugin because I think is already included in the StarterKit.

**Comment by Abdulrahmanelheyb** [comment]
> I got the error when I added an extension that was part of the `StarterKit` (e.g. the History extension). Simply removing the redundant package fixed it.

I saw after writing them a message 😅

**Comment by farouqaldori** [comment]
I faced this issue and the way I solved it is by going through my yarn.lock file and removing any references to promisemirror.

In my case, I had previously downloaded a package that depends on prosemirror which caused the conflict.

Hope this helps!

**Comment by joeyee2015** [comment]
> Same for me. I've cleared the yarn cache, removed `node_modules` and re-run `yarn install` multiple times.
> 
> **using:** yarn **tiptap version:** 1.19.1 (updated from 1.18.0)
> 
> ![Screen Shot 2019-05-10 at 8 11 39 PM](https://user-images.githubusercontent.com/1027918/57563820-da1e0a80-735f-11e9-81db-13c9baea926b.png)
> 
> **code:**
> 
> ```js
> import { Editor } from 'tiptap'
> 
> //...Vue stuff...
> 
> this.editor = new Editor({
>   content: doc,
>   extensions: [],
> })
> ```

I  removed `node_modules` and re-run `yarn install` multiple times. It works... 666

**Comment by fpaupier** [comment]
> Some further discussion on this here: #577
> 
> This appears related multiple versions of prosemirror-state being loaded. It can be worked around by adding the following (yarn) resolutions in your package.json:
> 
> ```
> "resolutions": {
>     "prosemirror-model": "1.8.2",
>     "prosemirror-state": "1.3.2",
>     "prosemirror-transform": "1.2.2",
>     "prosemirror-view": "1.13.4"
>   },
> ```
> 
> > To summarize, this is what I did:
> > Opened yarn.lock and found duplicates for every prosemirror package
> > For every such package, pinpointed its version in resolutions to prevent multiple versions of the same package from installing (you can try my resolutions above)
> > rm -rf node_modules
> > yarn cache clean
> > yarn install

I had the same issue because I installed both the `tiptap/starter-kit` and other extensions in my package.json. I removed the starter kit and listed specifically the extension required and it worked for me.

**Comment by kevin-lynch** [comment]
I had the same issue. In my case it was because I was running vue.js 2. To resolve the issue I uninstalled tiptop and reinstalled version 1

Uninstall
`npm uninstall tiptap tiptap-extensions`

Reinstall V1
`npm install tiptap@1 tiptap-extensions@1`

**Comment by desousar** [comment]
I encountered this problem when I updated my application from Vue 2 to Vue 3.
Naturally, I installed `@tiptap/pm` (standard install `@tiptap/vue-3 @tiptap/pm @tiptap/starter-kit`).
But in my package.json, I still had the `prosemirror-...`.

Solution: I deleted the old lines, deleted node_modules and in my case the yarn.lock and then I do a `yarn`

Doc: 
Tiptap is built on top of ProseMirror, which has a pretty powerful API. To access it, we provide the package @tiptap/pm. This package provides all important ProseMirror packages like prosemirror-state, prosemirror-view or prosemirror-model. (https://tiptap.dev/docs/editor/guide/prosemirror)

**Comment by Manaskhurana** [comment]
I have encountered this error when i have install latest version of tiptap

rangeerror: adding different instances of a keyed plugin (history$)

1. to fix this issue first install tiptap starter kit
2. delete node_modules and package-lock.json 
3. figure out the which modules is already install with started pack don't resinstall same modules if any
4. reinstall node_modules and  package-lock.json 
5. launch next.js again and your problem will gone
